name: Building of Docker Images and Pushing it to AWS ECR

on:
  push:
    branches: [ "master" ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1   
          
          
      - name: Building Database and Webapplication Docker Images and Pushing it to ECR
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd clo835_fall2022_assignment1/  
          ls -ltra
                    
          # Building Docker image for mysql
          docker build -f Dockerfile_mysql -t 105718917616.dkr.ecr.us-east-1.amazonaws.com/datab:v2.0 .
          docker push 105718917616.dkr.ecr.us-east-1.amazonaws.com/datab:v2.0

          # Building docker for webapp
          docker build -f Dockerfile -t 105718917616.dkr.ecr.us-east-1.amazonaws.com/web:v2.0 .
          docker push 105718917616.dkr.ecr.us-east-1.amazonaws.com/web:v2.0
